### ISSUE TITLE
Lack of my_util

### ISSUE THREAD

**Issue by B0GGY** [vincent341/S-ANS#3]
Hi, thanks for your contribution. But I found that there might be some problems running your code. Here is the error from the ans.py. 
ModuleNotFoundError: No module named 'my_util'
And I can not find this my_util in this repo. I really appreciate it if you could provide this missing file in your latest version.

**Comment by vincent341** [comment]
Hi. I have uploaded my_util folder. Please check it.

**Comment by B0GGY** [comment]
Thanks for you update! By the way, the function 'generate_topdown_allocentric_frontiermap' in visualization.py from the file occant_utils is missing as well. Would you mind updating this too?
